# Generated by Django 4.2.29 on 2026-04-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_sub",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "picture_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
